"""empty message

Revision ID: e16886791521
Revises: c7ed53847b3d
Create Date: 2018-12-23 13:05:14.307735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16886791521'
down_revision = 'c7ed53847b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'comment_num')
    # ### end Alembic commands ###
